### ISSUE TITLE
Needs a 64x64 and 128x128 icon

### ISSUE THREAD

**Issue by jgarciao** [flathub/io.exodus.Exodus#11]
Flathub.org (the website) gets the information about the apps from the appstream.xml file generated in the ostree repo. You can see the contents in your computer opening this file: /var/lib/flatpak/appstream/flathub/x86_64/active/appstream.xml

This app is not appearing in the website because it has some issues in the appstream information:

    * there is no `<icon>` tag for 64x64 and 128x128

**Comment by TingPing** [comment]
It uses an svg now, I thought appstream-util handled those now?

**Comment by jgarciao** [comment]
Last month it didn't:
- https://github.com/flathub/org.gnome.Weather/issues/2#issuecomment-456026946
- https://github.com/flathub/linux-store-backend/issues/10

**Comment by AHappyUser** [comment]
Should the `<icon> tag`  look like this?

`<icon type="remote" height="64" width="64">https://www.exodus.io/img/exodus-logo.svg</icon>`
`<icon type="remote" height="128" width="128">https://www.exodus.io/img/exodus-logo.svg</icon>`

**Comment by TingPing** [comment]
The SVG is already stored in the repo so no need to do `remote`. Probably just converting that to PNG of each size and installing them will solve it.

**Comment by AHappyUser** [comment]
@TingPing OK I change the icons to .PNG and made a pull request but don't know if it works.

**Comment by AHappyUser** [comment]
What is up with the flathubbot cant find the test build and get a `504 Gateway Time-out` error?

**Comment by AHappyUser** [comment]
I converted the SVG to PNG sizes 16x16, 32x32, 64x64, 128x128, 256x256, and 512x512 but Hicolor icons did not appear. Until I figure this out can I just add the two remote icon tags

`<icon type="remote" height="64" width="64">https://www.exodus.io/img/exodus-logo.svg</icon>`
`<icon type="remote" height="128" width="128">https://www.exodus.io/img/exodus-logo.svg</icon>`

**Comment by TingPing** [comment]
Remote icons really really suck.

**Comment by AHappyUser** [comment]
Great, I will eventually figure out how to fix the icon tag problem.  I just updated the GitHub repo to version 19.6.20.  Is there usually a delay before getting the update through the Flathub repository?

**Comment by TingPing** [comment]
There is a delay of some hours. You can go to the specific build on https://flathub.org/builds and hit `publish` manually though if needed.

**Comment by Wetrain** [comment]
Hi, the build logs are not showing issues with the icons anymore, however it fails because the example photos are too large

`   using PTY: False
builddir/files/share/appdata/io.exodus.Exodus.appdata.xml: FAILED:
• tag-missing           : <translation> not specified
• value-missing         :  is not present
• attribute-invalid     : <screenshot> width too large [https://www.exodus.io/desktop/img/portfolio-lsize.png] maximum is 1600px
• attribute-invalid     : <screenshot> height too large [https://www.exodus.io/desktop/img/portfolio-lsize.png] maximum is 900px
• aspect-ratio-invalid  : <screenshot> aspect ratio not 16:9 [https://www.exodus.io/desktop/img/portfolio-lsize.png]
• attribute-invalid     : <screenshot> width too large [https://www.exodus.io/desktop/img/send-receive-lsize.png] maximum is 1600px
• attribute-invalid     : <screenshot> height too large [https://www.exodus.io/desktop/img/send-receive-lsize.png] maximum is 900px
• aspect-ratio-invalid  : <screenshot> aspect ratio not 16:9 [https://www.exodus.io/desktop/img/send-receive-lsize.png]
• attribute-invalid     : <screenshot> width too large [https://www.exodus.io/desktop/img/exchange-assets-lsize.png] maximum is 1600px
• attribute-invalid     : <screenshot> height too large [https://www.exodus.io/desktop/img/exchange-assets-lsize.png] maximum is 900px
• aspect-ratio-invalid  : <screenshot> aspect ratio not 16:9 [https://www.exodus.io/desktop/img/exchange-assets-lsize.png]
• translations-required  : <name> has no translations
• translations-required  : <summary> has no translations
• translations-required  : <description> has no translations`

**Comment by TingPing** [comment]
They are just warnings.
