### ISSUE TITLE
Upstream involvement

### ISSUE THREAD

**Issue by barthalion** [flathub/io.exodus.Exodus#34]
FYI @AHappyUser, I have invited @ews to collaborators. He's a VP of eng. at Exodus and wanted to pick up maintenance of the application.

@ews Please let me know if we should invite more people from Exodus team.

**Comment by AHappyUser** [comment]
Sounds great!
Maybe the Exodus Team could add a flathub button to exodus.io ?

**Comment by GeorgesStavracas** [comment]
Seems like J.P. Puerta is not involved with Exodus anymore, and recently someone reported the company's customer support is instructing people not to use the Flatpak. Should we reach them out again and see what is going on?

**Comment by AHappyUser** [comment]
Yes If you could that wood be great.

**Comment by AHappyUser** [comment]
It wood be nice of Exodus wood officially support or maintain the Flatpak.

**Comment by Arcitec** [comment]
It's disappointing that Exodus wastes their energy shipping archaic, loose `.deb` and `.zip` files instead of joining this super simple Flatpak installer project. It's literally a super clean manifest file and some easy automatic flathubbot pull requests to accept periodically.

I'm definitely scared to get Exodus from a third party, but @AHappyUser you've spent years on this Flatpak and have done an amazing job. So you have earned my trust. Malicious people wouldn't have maintained something for 5 years!

And hey, the Flatpak definitely beats my own personal install script which was this janky stuff:

```sh
7z x ~/Downloads/exodus-linux-x64-*.zip -o"$HOME/Downloads/exodus-tmp"
mv ~/Downloads/exodus-tmp/Exodus-linux-x64 ~/.local/share/exodus-wallet
rm -rf ~/Downloads/exodus-tmp

7z x ~/Downloads/exodus-linux-x64-*.deb -o"$HOME/Downloads/exodus-deb-tmp"
7z e -r ~/Downloads/exodus-deb-tmp/data.tar -o"$HOME/Downloads/exodus-deb-tmp" "exodus.png"
mkdir -p ~/.local/share/icons/hicolor/128x128/apps
mv ~/Downloads/exodus-deb-tmp/exodus.png ~/.local/share/icons/hicolor/128x128/apps/
rm -rf ~/Downloads/exodus-deb-tmp
gtk-update-icon-cache

cd ~/.local/share/exodus-wallet
echo "\nIcon=$HOME/.local/share/icons/hicolor/128x128/apps/exodus.png" >> ~/.local/share/exodus-wallet/exodus.desktop
./install-desktop-file.sh
```

:D

I still wish Exodus themselves would help out. Maybe one day...

**Comment by AHappyUser** [comment]
It would be great to get involved in maintaining this package. 
I have a maintenance package simply because I use it. I'm happy that other people use it to.
